version: '3.9'

services:
  resume-site:
    build: .
    container_name: resume-site-nginx
    restart: "unless-stopped"
    ports:
      - "8087:80"
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resume-site.rule=Host(`brian.th3rogers.com`) || Host(`th3rogers.com`) || Host(`www.th3rogers.com`)"
      - "traefik.http.routers.resume-site.entrypoints=websecure"
      - "traefik.http.services.resume-site.loadbalancer.server.port=80"
      - "traefik.http.routers.resume-site.tls.certresolver=myresolver"
      - "traefik.http.middlewares.temp-redirect.redirectregex.regex=^(https?://)(.*).th3rogers.com/(.*)"
      - "traefik.http.middlewares.temp-redirect.redirectregex.replacement=$${1}brian.th3rogers.com/$${3}"
      - "traefik.http.routers.resume-site.middlewares=temp-redirect"

networks:
  public:
    external: true
    name: Public

